name: flutter_towerdefense_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.27.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.15
  custom_lint: ^0.7.5
  mockito: ^5.4.6
  build_runner: ^2.4.15
  flame_test: ^1.17.0 
  mocktail: ^1.0.0

dependency_overrides:
  analyzer: 7.3.0
  analyzer_plugin: 0.12.0
  custom_lint_visitor: 1.0.0+7.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/floor/
    - assets/images/indios_garimpeiros/
    - assets/images/market/
    - assets/images/
